/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * lap_dep.java
 *
 * Created on Apr 26, 2009, 11:12:51 AM
 */

package reportdebitur;
import java.io.BufferedReader;
import java.sql.*;
import java.io.File;
import java.io.FileInputStream;
import java.io.DataInputStream;
import java.io.IOException;
import java.io.InputStreamReader;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.util.Map;
import java.util.HashMap;
import java.util.Properties;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Irham
 */

public class lap_dep extends javax.swing.JFrame {
    Connection cn=null;
    Statement stmnt=null;
    Statement stmnt2=null;
    ResultSet rs=null;
    ResultSet rs2=null;
    ResultSet rs3=null;
    ResultSet rs4=null;
    /*Untuk Laporan Jasperreport*/
    String direktori;
    String report="realisasi2.jrxml";
    String lain="realisasi.jrxml";
    Map<String,Object> param=new HashMap<>();
    JasperReport jrpt = null;

    /*******************************/
    String nm_conn="Conn.txt";
    Properties prp=System.getProperties();
    String path_db=prp.getProperty("user.dir");
    String strline="";
    String[] isian=new String[10];
    
    /****************************************/
    public Integer tampungan;
    frmbulanan frmbln;
    /*Buat daftar bunga dan jadwal*/

    /** create by irham / irhamp@yahoo.com */
    public lap_dep() {
        initComponents();
        tampungan=0;
        setLocationRelativeTo(null);
        /*BACA FILE Conn.TXT*/

             try{
                    FileInputStream fistream=new FileInputStream(path_db+File.separatorChar+nm_conn);
                    DataInputStream in=new DataInputStream(fistream);
                    BufferedReader br=new BufferedReader(new InputStreamReader(in));
                    Integer n=0;
                    while((strline=br.readLine())!=null){
                        isian[n]=strline;
                        n=n+1;
                    }}
             catch(IOException io){
                 JOptionPane.showMessageDialog(this, io);
             }
             /****************************/

        try{
            Class.forName("com.mysql.jdbc.Driver");
            cn=DriverManager.getConnection(isian[0],isian[1],isian[2]);
            stmnt=cn.createStatement();
            stmnt2=cn.createStatement();
        }
        catch(ClassNotFoundException cls){
            JOptionPane.showMessageDialog(rootPane, "Error :"+cls);
        }
        catch(SQLException sqe){
            try {
                cn = DriverManager.getConnection(isian[0], isian[1],isian[2]);
                stmnt=cn.createStatement();
                stmnt2=cn.createStatement();

            } catch (SQLException ex) {
                Logger.getLogger(lap_dep.class.getName()).log(Level.SEVERE, null, ex);
            }

            JOptionPane.showMessageDialog(rootPane, "Error sambungan: "+sqe+" Sialahkan tekan OK");
            JOptionPane.showMessageDialog(rootPane, "Sambungan anda sudah diperbaikai");
        }
        setDefaultCloseOperation(EXIT_ON_CLOSE);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kode_dlr = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtjenis = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtstnk = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtnotapajak = new javax.swing.JTextField();
        jmlbln = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        kode_dlr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kode_dlrActionPerformed(evt);
            }
        });
        kode_dlr.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                kode_dlrKeyPressed(evt);
            }
        });

        jButton1.setText("LIHAT REPORT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("NO KREDIT");

        txtjenis.setEditable(false);
        txtjenis.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtjenisKeyPressed(evt);
            }
        });

        jLabel2.setText("JENIS PINJAMAN");

        jButton2.setText("TUTUP");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel3.setText("STNK");

        jLabel4.setText("NOTA PAJAK");

        jmlbln.setEditable(false);
        jmlbln.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                jmlblnCaretUpdate(evt);
            }
        });

        jLabel5.setText("JML BULAN");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addGap(38, 38, 38))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(kode_dlr, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jmlbln, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtjenis, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(38, 38, 38)
                        .addComponent(txtnotapajak, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jButton2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(38, 38, 38)
                        .addComponent(txtstnk, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(98, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kode_dlr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtjenis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jmlbln, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtstnk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtnotapajak, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addContainerGap(91, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void buatlaporan(){
        double a1=0.00;
        double a2=0.00;
        double pokoktrans=0.00;
        double bng=0.00;
        int jmlangs=0;
        double total=0.00;
        double keluar=0.00;
        Date tglakhir=null;
        Date tgl2=null;
        double provisi=0.00;
        double notariel=0.00;
            double administrasi=0.00;
            double materai=0.00;
        //Dibawah ini adalah proses input nilai ke paramater dan proses penampilan report
        //Properties prp=System.getProperties();
                try {
            Double tot1=0.00;
            rs3=stmnt.executeQuery("select * from kredit where no_rekening='"+ kode_dlr.getText() +"'");
            //JOptionPane.showMessageDialog(rootPane, rs3.getRow());
            while(rs3.next()){
                txtjenis.setText(rs3.getString("jenis_pinjaman"));
                bng=rs3.getDouble("SUKU_BUNGA_PER_ANGSURAN");
                jmlangs=rs3.getInt("jml_angsuran");
            }
            rs2=stmnt.executeQuery("select * from kretrans where no_rekening='"+ kode_dlr.getText() +"' and my_kode_trans='100'");
            while(rs2.next()){
                provisi=rs2.getDouble("provisi_trans");
                notariel=rs2.getDouble("notariel_trans");
                if(notariel==0 || (String.valueOf(notariel)==null)){
                    notariel=0;
                }
                materai=rs2.getDouble("materai_trans");
                administrasi=rs2.getDouble("adm_trans");
                total=provisi+notariel+materai+administrasi;
                keluar=rs2.getDouble("pokok_trans")-total;
               pokoktrans=rs2.getDouble("pokok_trans");
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, ex);
        } catch(NullPointerException es){
            JOptionPane.showMessageDialog(rootPane, es);
        }

        direktori=prp.getProperty("user.dir");/*untuk mengetahui direktori kerja*/
        String kdlr=kode_dlr.getText();
        double aa1=a1;
        double aa2=a2;
        double bungaperbulan=pokoktrans*bng/100;
        double jmlangsuran=pokoktrans +(pokoktrans*bng/100*jmlangs);
        String notapajak=txtnotapajak.getText();
        String stnk=txtstnk.getText();
        String total2=String.valueOf(total);
        String keluar2=String.valueOf(keluar);
        param.put("tglakhir", tglakhir);
        param.put("norek",kdlr);
        param.put("a11",aa1);
        param.put("a22",aa2);
        param.put("total1", total2);
        param.put("keluaran", keluar2);
        param.put("tanggal2", tgl2);
        param.put("bungaperbulan",bungaperbulan);
        param.put("jumlahangs",jmlangsuran);
        param.put("notapajak",notapajak);
        param.put("stnk",stnk);
        //String jenis="K02";String jenis2="K04";
    }
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
            
            Date tgl1=null;
            double provisi=0.00;
            double notariel=0.00;
            double administrasi=0.00;
            double materai=0.00;
       /************BACA FILE Conn.TXT***************/
       
            try{
                   FileInputStream fistream=new FileInputStream(path_db+File.separatorChar+nm_conn);
                   DataInputStream in=new DataInputStream(fistream);
                   BufferedReader br=new BufferedReader(new InputStreamReader(in));
                   Integer n=0;
                   while((strline=br.readLine())!=null){
                       isian[n]=strline;
                       n=n+1;
                   }}
            catch(IOException io){
                JOptionPane.showMessageDialog(this, io);
            }
         /****************************/

         buatlaporan();
        try{
            if(Integer.valueOf(String.valueOf(txtjenis.getText()).substring(2))!=1 )
                {
                    frmbln=new frmbulanan(this);
                    frmbln.setVisible(true);
                    frmbln.setLocation(155, 200);
                }
            else{
                jrpt=JasperCompileManager.compileReport(direktori+ File.separatorChar + lain);
                JasperPrint jrprt=JasperFillManager.fillReport(jrpt, param, cn);
                JasperViewer.viewReport(jrprt,false);//JOptionPane.showMessageDialog(rootPane, "dua");
                }
            }
        catch(Exception exc)
            {
            JOptionPane.showMessageDialog(rootPane, "Data Tidak ditemukan");
            }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        //this.setDefaultCloseOperation(1);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void kode_dlrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kode_dlrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kode_dlrActionPerformed

    private void kode_dlrKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_kode_dlrKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode()==10)
        {
                kode_dlr.transferFocus();
        }
    }//GEN-LAST:event_kode_dlrKeyPressed

    private void txtjenisKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtjenisKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==10){
            txtjenis.transferFocus();
        }
    }//GEN-LAST:event_txtjenisKeyPressed

    private void jmlblnCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_jmlblnCaretUpdate
        // TODO add your handling code here:
           double bunga=0.00;
           double pokok=0.00;
           double totpokok=0.00;
           double totbunga=0.00;
           int lamaangs=0;
           int mykodetrans;
           Date jadwal;
           Date jadwalawal;
           Integer  i=new Integer(Integer.valueOf(jmlbln.getText()));
         try
         {
         
            cn=DriverManager.getConnection(isian[0],isian[1],isian[2]);
            stmnt=cn.createStatement();
            stmnt2=cn.createStatement();
            stmnt2.executeUpdate("delete from datareport");
            rs4=stmnt.executeQuery("select JML_ANGSURAN from kredit WHERE NO_REKENING='"+ kode_dlr.getText() +"'");
            while(rs4.next()){
                lamaangs=rs4.getInt(1);
            }
            int lompatan=lamaangs/i;
            rs4=stmnt.executeQuery("select * from kretrans where no_rekening='"+ kode_dlr.getText() +"'  AND (MY_KODE_TRANS='200' or MY_KODE_TRANS='100') ORDER BY TGL_TRANS");
            int j=0;
            int k=0;
            jadwalawal=null;
            while(rs4.next()){
                mykodetrans=rs4.getInt("my_kode_trans");
                if(mykodetrans==200)
                {
                    pokok=pokok+rs4.getDouble("pokok_trans");
                    bunga=bunga+rs4.getDouble("bunga_trans");
                }
                if(mykodetrans==100){
                    jadwalawal=rs4.getDate("tgl_trans");
                    bunga=rs4.getDouble("bunga_trans")/lamaangs*i;
                    stmnt2.executeUpdate("insert into datareport(no_rekening,tgljadwal,pokok,bunga) values('"+ kode_dlr.getText() +"','"+ jadwalawal +"','"+ pokok +"','"+ bunga +"')");                                            
                    pokok=0.00;
                    bunga=0.00;
                }
                jadwal=rs4.getDate("tgl_trans");
                if(j==i){
                    ++k;
                    if(lompatan==k){
                       stmnt2.executeUpdate("insert into datareport(no_rekening,tgljadwal,pokok,bunga) values('"+ kode_dlr.getText() +"','"+ jadwal +"','"+ pokok +"','0')");
                    }
                    else{
                    stmnt2.executeUpdate("insert into datareport(no_rekening,tgljadwal,pokok,bunga) values('"+ kode_dlr.getText() +"','"+ jadwal +"','"+ pokok +"','"+ bunga +"')");
                    }
                    j=0;
                    pokok=0.00;
                    bunga=0.00;
                }
                 j++;
            }           
             buatlaporan();
            jrpt=JasperCompileManager.compileReport(direktori+ File.separatorChar + report);
             JasperPrint jrprt=JasperFillManager.fillReport(jrpt, param, cn);
             JasperViewer.viewReport(jrprt,false);
                     }
         catch(Exception ex){
          System.out.println(ex);
          System.out.println(ex.getStackTrace()[0].getClassName());
          System.out.println(ex.getStackTrace()[0].getMethodName());
          System.out.println(ex.getStackTrace()[0].getLineNumber());
      }

    }//GEN-LAST:event_jmlblnCaretUpdate

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new lap_dep().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    public javax.swing.JTextField jmlbln;
    private javax.swing.JTextField kode_dlr;
    private javax.swing.JTextField txtjenis;
    private javax.swing.JTextField txtnotapajak;
    private javax.swing.JTextField txtstnk;
    // End of variables declaration//GEN-END:variables

}
